name: Pylint and Notebook Cleaning

on: [push]
 
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint nbconvert nbstripout

    - name: Clean notebooks using nbstripout
      run: |
        # Clean notebooks in the subfolder (replace 'notebooks' with your subfolder name)
        find notebooks -name "*.ipynb" -exec nbstripout {} +

    - name: Analysing the code with pylint
      run: |
        pylint notebooks