name: Pylint and Notebook Cleaning

on: [push]
 
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pylint nbconvert nbstripout nbqa

    - name: Clean Jupyter Notebooks (Windows)
      shell: cmd
      run: for /r %%F in (*.ipynb) do nbstripout "%%F"

