name: Pylint and Notebook Cleaning

on: [push]
 
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install pylint nbconvert nbstripout

    - name: Clean notebooks using nbstripout
      shell: cmd
      run: |
        for /r notebooks %%f in (*.ipynb) do nbstripout "%%f"

    - name: Analysing the code with pylint
      shell: cmd
      run: |
        pylint notebooks
